# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [2]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [3]:
A = np.arange(1, 16).reshape(3,5)


In [4]:
print(A.ndim)

2


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [6]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [7]:
print(B - C)
print(B * C)
print(B @ C)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [6]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(np.exp(B))
print()
print(B.min())
print()
print(B.min(axis=1))
print()
print(B.min(axis=0))
print()
print(np.argmin(B))
print()
print(np.argmin(B, axis=1))
print()
print(B.sum())
print()
print(B.mean(axis=0))
print()
print(np.median(B, axis=0))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

1

[1 4 7]

[1 2 3]

0

[0 0 0]

45

[4. 5. 6.]

[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [26]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [34]:
print(A[1])
print(A[1,:])
print(A[1,...])

[ 6  7  8  9 10]
[ 6  7  8  9 10]
[ 6  7  8  9 10]


**Answer:**

When we specify fewer indices than the axes of the array then it is considered a complete slice. So A[1] returns the same answer as A[1,:], additionally we can use ... to represent all the colons needed to complete the slice, so A[1,...] returns the same as the other two examples as well.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [31]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [32]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [35]:
# numpy arrays come with the .flat attribute which allow us to iterate through the array elementwise

for i in A.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [146]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


Answer: we create a as an array containing values ranging from 0 to 29, since nothing else is specified it defaults to one dimensional array. Then we create b as a multidimensional reshaping of a which will consist of 2 blocks with 3 rows each, the -1 functions as a sort of autofill that calculates how many columns would be needed so that array b could contain all values in array a. 

b is 3 dimensional and has 2 axes

array([[3, 4, 6],
       [5, 6, 2],
       [5, 7, 8]])

# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [37]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [38]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [39]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [51]:
def add_mult_matrices(x, y, math):
    isinstance([x,y], np.ndarray) == True
    math == 'add' or 'mult'
    if math == 'add' and x.shape == y.shape:
        return x + y
    elif math == 'add' and x.shape != y.shape:
        raise Exception ('Matrices must be of the same shape')
        
    
    if math == 'mult' and np.size(x, axis=1) == np.size(y, axis=0):
        return x @ y
    elif math == 'mult' and np.size(x, axis=1) != np.size(y, axis=0):
        raise Exception ('The number of columns in the first matrix must equal the number of rows in the second matrix')
        
    

In [52]:
A = np.array([2, 1, -1, 1, -1, 1]).reshape(2,3)
B = np.array([4, -2, 1, 2, -4, -2]).reshape(2,3)
C = np.array([1, 2, 2,1]).reshape(2,2)
D = np.array([3,4,4,3]).reshape(2,2)
E = np.array([1,2]).reshape(2,1)
I = np.array([1, 0, 0, 1]).reshape(2,2)

add_mult_matrices(E, C, 'mult')

Exception: The number of columns in the first matrix must equal the number of rows in the second matrix

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. 

In [56]:

print('Uppgift 10.1.1')
# Uppgift 10.1.1. Definiera vektorn x enligt nedan.
# x = (4, 3)
# (a) Vilken dimension har vektorn x?
# (b) Ber¨akna 5x.
# (c) Ber¨akna 3x.
# (d) Ber¨akna 5x + 3x.
# (e) Ber¨akna 8x.
# (f) Ber¨akna 4x − x.
# (g) Ber¨akna x⊤, vilken blir den nya dimensionen efter att
# transponeringen utf¨orts?
# (h) ¨Ar x + x⊤ definierat?
# (i) Ber¨akna ∥x∥.

x = np.array([4,3])

print('a:', x.ndim) # a
print('b:', x*5) # b
print('c:', x*3) # c
print('d:', (x*5)+(x*3)) # d
print('e:', x*8) # e
print('f:', (x*4)-x) # f
print('g:', (np.atleast_2d(x).T), (np.atleast_2d(x).T).ndim) # g
print('h:', x+(np.atleast_2d(x).T)) # matematiskt är det x + xT inte definerad pga de två vektorna inte har samma dimensioner, 
                              #numpy kommer ändå räkna det igenom sin broadcast feature
print('i:', np.linalg.norm(x))

print('Uppgift 10.1.2.')
# Definiera vektorn v enligt nedan.
# v =
# 3
# 7
# 0
# 11
# (a) Vilken dimension har vektorn v?
# (b) Ber¨akna 2v.
# (c) Ber¨akna 5v + 2v.
# (d) Ber¨akna 4v − 2v.
# (e) Ber¨akna v⊤, vilken blir den nya dimensionen efter att
# transponeringen utf¨orts?
# (f) Ber¨akna ∥v∥

v = np.array(([3], [7], [0],[11]))

print('a:', v.ndim) # a
print('b:', v*2) # b
print('c:', (v*5)+(v*2))# c
print('d:', (v*4)-(v*2))# d
print('e:', v.T, v.ndim)# e
print('f:', np.linalg.norm(v))# f

# Uppgift 10.1.3. Definiera vektorerna v1 = (4, 3, 1, 5) och
# v2 = (2, 3, 1, 1).
# (a) Ber¨akna ∥v1∥.
# (b) Ber¨akna ∥v1 − v2∥.
print('Uppgift 10.1.3')
v1 = np.array([4,3,1,5])
v2 = np.array([2,3,1,1])

print('a:', np.linalg.norm(v1))
print('b:', np.linalg.norm(v1-v2))

Uppgift 10.1.1
a: 1
b: [20 15]
c: [12  9]
d: [32 24]
e: [32 24]
f: [12  9]
g: [[4]
 [3]] 2
h: [[8 7]
 [7 6]]
i: 5.0
Uppgift 10.1.2.
a: 2
b: [[ 6]
 [14]
 [ 0]
 [22]]
c: [[21]
 [49]
 [ 0]
 [77]]
d: [[ 6]
 [14]
 [ 0]
 [22]]
e: [[ 3  7  0 11]] 2
f: 13.379088160259652
Uppgift 10.1.3
a: 7.14142842854285
b: 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

In [57]:
# Uppgift 10.2.1. Definiera matriserna:
# (a) 2A
# (b) B − 2A
# (c) 3C − 2E
# (d) 2D − 3C
# (e) D⊤ + 2D
# (f) 2C⊤ − 2D⊤
# (g) A⊤ − B
# (h) AC
# (i) CD
# (j) CB
# (k) CI
# (l) AB⊤

A = np.array([2, 1, -1, 1, -1, 1]).reshape(2,3)
B = np.array([4, -2, 1, 2, -4, -2]).reshape(2,3)
C = np.array([1, 2, 2,1]).reshape(2,2)
D = np.array([3,4,4,3]).reshape(2,2)
E = np.array([1,2]).reshape(2,1)
I = np.array([1, 0, 0, 1]).reshape(2,2)
print('Uppgift 10.2.1.')
print('a:', 2*A)# a
print('b:', B-(2*A)) # b
print('c:', (3*C)-(2*E))# c
print('d:', (2*D)-(3*C)) # d
print('e:', (D.T)+(2*D)) # e
print('f:', (2*C.T)-(2*D.T)) # f
print('g:', '(A.T)-B är ej definerad')
print('h:', 'A @ C ej definerad')
print('i:', C @ D) # i
print('j:', C @ B) # j
print('k:', C @ I) # k
print('l:', A @ B.T) # l
print()
print('Uppgift 10.2.2')
# Uppgift 10.2.2. Definiera matrisen
# Ber¨akna AAT
A = np.array([2, 3, 4, 5, 4, 1]).reshape(2,3)
print(A@A.T)
print("Uppgift 10.2.3.")

A = np.array([1, 2, 2, 4]).reshape(2,2)
B = np.array([2, 1, 1,3]).reshape(2,2)
C = np.array([4, 3, 0, 2]).reshape(2,2)

print(A@B, A@C, B, C)
# Verifiera att AB = AC men att B̸ = C. Vad vi vill demon-
# strera med detta exemplet ¨ar att vi har definierat ett nytt
# matematiskt objekt (matriser i detta fallet) och att de ”van-
# liga reglerna” f¨or aritmetik som vi l¨art oss fr˚an grundskolan
# inte n¨odv¨andigtvis g¨aller ¨aven h¨ar.





Uppgift 10.2.1.
a: [[ 4  2 -2]
 [ 2 -2  2]]
b: [[ 0 -4  3]
 [ 0 -2 -4]]
c: [[ 1  4]
 [ 2 -1]]
d: [[3 2]
 [2 3]]
e: [[ 9 12]
 [12  9]]
f: [[-4 -4]
 [-4 -4]]
g: (A.T)-B är ej definerad
h: A @ C ej definerad
i: [[11 10]
 [10 11]]
j: [[  8 -10  -3]
 [ 10  -8   0]]
k: [[1 2]
 [2 1]]
l: [[5 2]
 [7 4]]

Uppgift 10.2.2
[[29 26]
 [26 42]]
Uppgift 10.2.3.
[[ 4  7]
 [ 8 14]] [[ 4  7]
 [ 8 14]] [[2 1]
 [1 3]] [[4 3]
 [0 2]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [5]:
v1 = np.arange(4)
v2 = v1[-2:]
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [7]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[  0   1   2 123]


In [8]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
